// Generated by scripts/build-site-predictions.mjs; do not edit by hand.
import type { TournamentPredictionCatalog } from "./tournamentPredictionData.types";

export const TOURNAMENT_PREDICTIONS = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-07T23:32:15.013Z",
  "tournaments": [
    {
      "id": "startgg:event:1503439",
      "name": "Riptide 2026",
      "eventName": "Melee Singles",
      "startDate": "2026-09-12",
      "sourceUrl": "https://www.start.gg/tournament/riptide-2026-4/event/melee-singles",
      "sourceSha256": "d804b651ddd2fa5d72cd612673e6076fb16eb5701739256d4315d26dafe22796",
      "snapshot": {
        "fetchedAt": "2026-09-07T23:32:15.013Z",
        "state": "CREATED",
        "entrantCount": 565
      },
      "scenario": {
        "kind": "seed-projected-top-16",
        "label": "Top-16 seed projection",
        "explanation": "Current root seeds 1–16 are assumed to survive pools and occupy the matching Top-16 phase positions; model favorites then advance through the published Top-16 and Top-8 routing.",
        "missingPoolNames": [
          "J205",
          "L204",
          "M203",
          "M205",
          "M206"
        ],
        "missingEntrantCount": 88
      },
      "training": {
        "events": 5,
        "sets": 8208,
        "datasetSha256": "90b7c09e4b613a2882fe9618c28da9b880480508113344c1f876aa64afae44a9",
        "evaluationRunHash": "57d348b1fa4846a4d0e45bce04d35497abbcc7ccd0fff2628421c7666346b313"
      },
      "defaultModelId": "regularized-bt-recent-form",
      "players": [
        {
          "id": "startgg:player:1004",
          "name": "Hungrybox",
          "seed": 1
        },
        {
          "id": "startgg:player:15634",
          "name": "lloD",
          "seed": 2
        },
        {
          "id": "startgg:player:1028",
          "name": "Wizzrobe",
          "seed": 3
        },
        {
          "id": "startgg:player:2011959",
          "name": "RapMonster",
          "seed": 4
        },
        {
          "id": "startgg:player:72157",
          "name": "Joshman",
          "seed": 5
        },
        {
          "id": "startgg:player:16105",
          "name": "Jmook",
          "seed": 6
        },
        {
          "id": "startgg:player:147424",
          "name": "Krudo",
          "seed": 7
        },
        {
          "id": "startgg:player:282043",
          "name": "Ossify",
          "seed": 8
        },
        {
          "id": "startgg:player:6544",
          "name": "Magi",
          "seed": 9
        },
        {
          "id": "startgg:player:3561",
          "name": "Ginger",
          "seed": 10
        },
        {
          "id": "startgg:player:16342",
          "name": "Axe",
          "seed": 11
        },
        {
          "id": "startgg:player:4107",
          "name": "n0ne",
          "seed": 12
        },
        {
          "id": "startgg:player:631158",
          "name": "MOF",
          "seed": 13
        },
        {
          "id": "startgg:player:3357",
          "name": "Spark",
          "seed": 14
        },
        {
          "id": "startgg:player:318568",
          "name": "Preeminent",
          "seed": 15
        },
        {
          "id": "startgg:player:63995",
          "name": "404Cray",
          "seed": 16
        }
      ],
      "models": [
        {
          "id": "regularized-bt-recent-form",
          "name": "Regularized Bradley-Terry + seed + recent form",
          "shortName": "Regularized BT + seed + form",
          "explanation": "Uses categorical player IDs, initial seeds, and pre-event recent form. Historical seed value is shown only in the separate seed sensitivity; character is not included and optimizer reliability still needs work.",
          "recommended": true,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.177533,
            "logLoss": 0.55313
          },
          "championId": "startgg:player:1004",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:15634",
            "startgg:player:1028",
            "startgg:player:2011959",
            "startgg:player:72157",
            "startgg:player:16105",
            "startgg:player:6544",
            "startgg:player:3561"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.974511,
                0.025489
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.736718,
                0.263282
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.948,
                0.052
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.769231,
                0.230769
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.616914,
                0.383086
              ],
              "predictedWinnerId": "startgg:player:4107",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.70287,
                0.29713
              ],
              "predictedWinnerId": "startgg:player:6544",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.860024,
                0.139976
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.834754,
                0.165246
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:4107"
              ],
              "probabilities": [
                0.811748,
                0.188252
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:6544"
              ],
              "probabilities": [
                0.39002,
                0.60998
              ],
              "predictedWinnerId": "startgg:player:6544",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.663705,
                0.336295
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.25072,
                0.74928
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.835119,
                0.164881
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.548928,
                0.451072
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.525586,
                0.474414
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.258155,
                0.741845
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.802074,
                0.197926
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.675072,
                0.324928
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.616036,
                0.383964
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.721769,
                0.278231
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.548928,
                0.451072
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.721769,
                0.278231
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        },
        {
          "id": "higher-seed",
          "name": "Higher seed (historical availability assumed)",
          "shortName": "Higher seed",
          "explanation": "Always favors the better initial seed at one training-calibrated rate. It ignores player history, recent form, and character.",
          "recommended": false,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.189191,
            "logLoss": 0.569096
          },
          "championId": "startgg:player:1004",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:15634",
            "startgg:player:1028",
            "startgg:player:2011959",
            "startgg:player:72157",
            "startgg:player:16105",
            "startgg:player:147424",
            "startgg:player:282043"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:4107",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:6544",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:4107"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:6544"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:147424",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:282043",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.234105,
                0.765895
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.234105,
                0.765895
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.765895,
                0.234105
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        },
        {
          "id": "glicko2",
          "name": "Glicko-2 (event rating periods)",
          "shortName": "Glicko-2",
          "explanation": "Rates players with both estimated strength and rating uncertainty, updating once per event. Unseen players begin at the shared default.",
          "recommended": false,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.226722,
            "logLoss": 0.64356
          },
          "championId": "startgg:player:1004",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:147424",
            "startgg:player:16105",
            "startgg:player:72157",
            "startgg:player:16342",
            "startgg:player:1028",
            "startgg:player:3357",
            "startgg:player:3561"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.766067,
                0.233933
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.456949,
                0.543051
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.429372,
                0.570628
              ],
              "predictedWinnerId": "startgg:player:147424",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.437025,
                0.562975
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.523207,
                0.476793
              ],
              "predictedWinnerId": "startgg:player:4107",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.455158,
                0.544842
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.788204,
                0.211796
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.669352,
                0.330648
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:4107"
              ],
              "probabilities": [
                0.563658,
                0.436342
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.428677,
                0.571323
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.410546,
                0.589454
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.266353,
                0.733647
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.604936,
                0.395064
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.37233,
                0.62767
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.516611,
                0.483389
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3357",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.431925,
                0.568075
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.372856,
                0.627144
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.499275,
                0.500725
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.562925,
                0.437075
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.542475,
                0.457525
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.499555,
                0.500445
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.541696,
                0.458304
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        },
        {
          "id": "recency-elo",
          "name": "Recency-weighted event-batch Elo",
          "shortName": "Recency Elo",
          "explanation": "Builds player ratings from prior sets, downweights older events, and updates every event as one batch.",
          "recommended": false,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.235321,
            "logLoss": 0.662761
          },
          "championId": "startgg:player:1004",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:147424",
            "startgg:player:16105",
            "startgg:player:72157",
            "startgg:player:16342",
            "startgg:player:1028",
            "startgg:player:3357",
            "startgg:player:3561"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.727942,
                0.272058
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.444076,
                0.555924
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.412402,
                0.587598
              ],
              "predictedWinnerId": "startgg:player:147424",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.459997,
                0.540003
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.453652,
                0.546348
              ],
              "predictedWinnerId": "startgg:player:318568",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.405336,
                0.594664
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.740817,
                0.259183
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.630956,
                0.369044
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.534747,
                0.465253
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.373263,
                0.626737
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.385738,
                0.614262
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.365502,
                0.634498
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.61544,
                0.38456
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.401695,
                0.598305
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.449414,
                0.550586
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3357",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.481545,
                0.518455
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.402603,
                0.597397
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.479,
                0.521
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.539065,
                0.460935
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.556219,
                0.443781
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.500944,
                0.499056
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.556219,
                0.443781
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        },
        {
          "id": "dynamic-bradley-terry",
          "name": "Dynamic Bradley–Terry",
          "shortName": "Dynamic Bradley–Terry",
          "explanation": "Fits player strength jointly within each event, then decays and shrinks that strength between events. It does not use seed.",
          "recommended": false,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.243491,
            "logLoss": 0.678742
          },
          "championId": "startgg:player:16105",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:147424",
            "startgg:player:16105",
            "startgg:player:72157",
            "startgg:player:16342",
            "startgg:player:1028",
            "startgg:player:3357",
            "startgg:player:3561"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.722698,
                0.277302
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.375683,
                0.624317
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.464182,
                0.535818
              ],
              "predictedWinnerId": "startgg:player:147424",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.43329,
                0.56671
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.45924,
                0.54076
              ],
              "predictedWinnerId": "startgg:player:318568",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.438732,
                0.561268
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.808534,
                0.191466
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.612887,
                0.387113
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.570889,
                0.429111
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.419575,
                0.580425
              ],
              "predictedWinnerId": "startgg:player:3357",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.361102,
                0.638898
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.321058,
                0.678942
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.511494,
                0.488506
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.309649,
                0.690351
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.443823,
                0.556177
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:3357",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.41282,
                0.58718
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.34854,
                0.65146
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.507367,
                0.492633
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.515663,
                0.484337
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.451901,
                0.548099
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.495828,
                0.504172
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "model",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.543962,
                0.456038
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "model",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        },
        {
          "id": "neutral",
          "name": "Neutral 50/50",
          "shortName": "Neutral 50/50",
          "explanation": "Gives both players 50%. Better seed is used only as a display tie-break so the path can continue; that is not model evidence.",
          "recommended": false,
          "heldOut": {
            "predictions": 6244,
            "events": 4,
            "brier": 0.25,
            "logLoss": 0.693147
          },
          "championId": "startgg:player:1004",
          "top8PlayerIds": [
            "startgg:player:1004",
            "startgg:player:15634",
            "startgg:player:1028",
            "startgg:player:2011959",
            "startgg:player:72157",
            "startgg:player:16105",
            "startgg:player:147424",
            "startgg:player:282043"
          ],
          "matches": [
            {
              "id": "A",
              "label": "Winners quarterfinal A",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:282043"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "B",
              "label": "Winners quarterfinal B",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "C",
              "label": "Winners quarterfinal C",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:147424"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "D",
              "label": "Winners quarterfinal D",
              "phase": "top16",
              "bracket": "upper",
              "round": "winners-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "J",
              "label": "Lower initial J",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:4107",
                "startgg:player:318568"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:4107",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "K",
              "label": "Lower initial K",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:6544",
                "startgg:player:3357"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:6544",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "L",
              "label": "Lower initial L",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:16342",
                "startgg:player:63995"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:16342",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "M",
              "label": "Lower initial M",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-initial",
              "playerIds": [
                "startgg:player:3561",
                "startgg:player:631158"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:3561",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "N",
              "label": "Lower round 2 N",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:16105",
                "startgg:player:4107"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "O",
              "label": "Lower round 2 O",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:6544"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:147424",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "P",
              "label": "Lower round 2 P",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:72157",
                "startgg:player:16342"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "Q",
              "label": "Lower round 2 Q",
              "phase": "top16",
              "bracket": "lower",
              "round": "lower-round-2",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:3561"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:282043",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "WSF-A",
              "label": "Winners semifinal A",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "WSF-B",
              "label": "Winners semifinal B",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-semifinal",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LR1-A",
              "label": "Lower round 1 A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:282043",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:72157",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LR1-B",
              "label": "Lower round 1 B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-round-1",
              "playerIds": [
                "startgg:player:147424",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:16105",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LQF-A",
              "label": "Lower quarterfinal A",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:72157"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LQF-B",
              "label": "Lower quarterfinal B",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-quarterfinal",
              "playerIds": [
                "startgg:player:2011959",
                "startgg:player:16105"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:2011959",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LSF",
              "label": "Lower semifinal",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-semifinal",
              "playerIds": [
                "startgg:player:1028",
                "startgg:player:2011959"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1028",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "WF",
              "label": "Winners final",
              "phase": "top8",
              "bracket": "upper",
              "round": "winners-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "LF",
              "label": "Lower final",
              "phase": "top8",
              "bracket": "lower",
              "round": "lower-final",
              "playerIds": [
                "startgg:player:15634",
                "startgg:player:1028"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:15634",
              "decision": "lower-seed-number",
              "isReset": false
            },
            {
              "id": "GF",
              "label": "Grand final",
              "phase": "top8",
              "bracket": "final",
              "round": "grand-final",
              "playerIds": [
                "startgg:player:1004",
                "startgg:player:15634"
              ],
              "probabilities": [
                0.5,
                0.5
              ],
              "predictedWinnerId": "startgg:player:1004",
              "decision": "lower-seed-number",
              "isReset": false
            }
          ],
          "placements": [
            {
              "placement": 1,
              "playerId": "startgg:player:1004"
            },
            {
              "placement": 2,
              "playerId": "startgg:player:15634"
            },
            {
              "placement": 3,
              "playerId": "startgg:player:1028"
            },
            {
              "placement": 4,
              "playerId": "startgg:player:2011959"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:72157"
            },
            {
              "placement": 5,
              "playerId": "startgg:player:16105"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:147424"
            },
            {
              "placement": 7,
              "playerId": "startgg:player:282043"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:6544"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:3561"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:16342"
            },
            {
              "placement": 9,
              "playerId": "startgg:player:4107"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:631158"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:3357"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:318568"
            },
            {
              "placement": 13,
              "playerId": "startgg:player:63995"
            }
          ]
        }
      ],
      "caveats": [
        "Experimental seed projection, not a confirmed later-round Start.gg bracket or full-field simulation.",
        "Later opponents are inferred by advancing each model's local favorite; percentages are raw conditional set estimates, not title odds or confidence intervals.",
        "Start.gg still labels this event CREATED, and entrants or routing can change after the snapshot.",
        "Five selected 2025 majors supply the training data; historical seed availability is assumed.",
        "Character is not a feature, and historical seed value is supported only by the separately labeled sensitivity."
      ]
    }
  ]
} satisfies TournamentPredictionCatalog;
