// Generated by scripts/build-tournament-backtest-data.mjs; do not edit by hand.
import type { TournamentPredictionBacktestBundle } from "./tournamentPredictionBacktestData.types";

export const TOURNAMENT_PREDICTION_BACKTEST = {
  "schemaVersion": 1,
  "kind": "tournament-prediction-public-backtest-v1",
  "status": "exploratory-not-confirmatory",
  "coverage": {
    "events": 83,
    "sets": 74891,
    "scoringUnit": "eligible realized target set"
  },
  "modes": [
    {
      "id": "strict-seeds",
      "label": "Strict seeds",
      "description": "Reported-chronology retrospective with seeds observed before cutoff only",
      "allowHistoricalSeeds": false,
      "snapshotVerified": false,
      "selectedModel": null,
      "productize": false,
      "models": [
        {
          "id": "regularized-bt-recent-form",
          "name": "Regularized Bradley-Terry + seed + recent form",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.562934109176196,
            "brier": 0.19031575980337323,
            "accuracy": 0.6904744934791905,
            "auc": 0.7700084930585407
          },
          "pooledCoverage": 0.46634442055787745,
          "tuning": {
            "matureEvents": 30,
            "fallbackEvents": 6,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 37,
              "innerSelected": 30
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.014013804073625687,
                "interval95": {
                  "lower": -0.029633218792975032,
                  "upper": 0.0013086961509352433
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.006808228015653625,
                "interval95": {
                  "lower": -0.01327143156194606,
                  "upper": -0.0002473319406319498
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "regularized-bt-default",
                "isDefault": true,
                "options": {
                  "abilityL2": 2,
                  "featureL2": 2,
                  "formHalfLifeDays": 180,
                  "formPrior": 6,
                  "formRatingK": 24,
                  "formRatingScale": 400,
                  "maxIterations": 300,
                  "tolerance": 1e-7
                },
                "count": 53,
                "frequency": 0.6385542168674698
              },
              {
                "candidateId": "regularized-bt-ability-l2-1",
                "isDefault": false,
                "options": {
                  "abilityL2": 1,
                  "featureL2": 2,
                  "formHalfLifeDays": 180,
                  "formPrior": 6,
                  "formRatingK": 24,
                  "formRatingScale": 400,
                  "maxIterations": 300,
                  "tolerance": 1e-7
                },
                "count": 30,
                "frequency": 0.3614457831325301
              }
            ]
          }
        },
        {
          "id": "higher-seed",
          "name": "Higher seed",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.6931471805599356,
            "brier": 0.25,
            "accuracy": 0.5,
            "auc": 0.5
          },
          "pooledCoverage": 0,
          "tuning": {
            "matureEvents": 0,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 83,
              "warmupDefault": 0,
              "innerUnavailableDefault": 0,
              "innerSelected": 0
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              },
              "brier": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "higher-seed-default",
                "isDefault": true,
                "options": {},
                "count": 83,
                "frequency": 1
              }
            ]
          }
        },
        {
          "id": "glicko2",
          "name": "Event-period Glicko-2",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5524903255444148,
            "brier": 0.1875557928899399,
            "accuracy": 0.7028992493838621,
            "auc": 0.788132780356054
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.00525618047072753,
                "interval95": {
                  "lower": -0.007871639823734866,
                  "upper": -0.002825108468792241
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.0013394384558493662,
                "interval95": {
                  "lower": -0.002101848787506338,
                  "upper": -0.0005687334289171762
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "glicko2-rd500",
                "isDefault": false,
                "options": {
                  "convergenceTolerance": 0.000001,
                  "initialRating": 1500,
                  "initialRd": 500,
                  "initialVolatility": 0.06,
                  "maxIterations": 100,
                  "ratingScale": 173.7178,
                  "tau": 0.5
                },
                "count": 67,
                "frequency": 0.8072289156626506
              },
              {
                "candidateId": "glicko2-rd350",
                "isDefault": true,
                "options": {
                  "convergenceTolerance": 0.000001,
                  "initialRating": 1500,
                  "initialRd": 350,
                  "initialVolatility": 0.06,
                  "maxIterations": 100,
                  "ratingScale": 173.7178,
                  "tau": 0.5
                },
                "count": 16,
                "frequency": 0.1927710843373494
              }
            ]
          }
        },
        {
          "id": "recency-elo",
          "name": "Recency-weighted Elo",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5822561188545007,
            "brier": 0.19723031509419217,
            "accuracy": 0.6993079542312147,
            "auc": 0.7793423070135965
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.020607326913651275,
                "interval95": {
                  "lower": -0.028142517600513846,
                  "upper": -0.01136044551783676
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.010089851512747511,
                "interval95": {
                  "lower": -0.011843045684254502,
                  "upper": -0.008203348579529625
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "recency-elo-k64-h730",
                "isDefault": false,
                "options": {
                  "halfLifeDays": 730,
                  "k": 64,
                  "scale": 400
                },
                "count": 67,
                "frequency": 0.8072289156626506
              },
              {
                "candidateId": "recency-elo-k32-h730",
                "isDefault": true,
                "options": {
                  "halfLifeDays": 730,
                  "k": 32,
                  "scale": 400
                },
                "count": 16,
                "frequency": 0.1927710843373494
              }
            ]
          }
        },
        {
          "id": "dynamic-bradley-terry",
          "name": "Dynamic Bradley-Terry",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5935548858160498,
            "brier": 0.20506119489293312,
            "accuracy": 0.6485950482528792,
            "auc": 0.7267195423330035
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.01384443169032955,
                "interval95": {
                  "lower": -0.017804798177139383,
                  "upper": -0.009206226151694722
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.005989713485113392,
                "interval95": {
                  "lower": -0.007211223361240749,
                  "upper": -0.004729193900347815
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "dynamic-bt-h730-r1",
                "isDefault": false,
                "options": {
                  "halfLifeDays": 730,
                  "maxIterations": 300,
                  "ridge": 1,
                  "tolerance": 1e-9
                },
                "count": 66,
                "frequency": 0.7951807228915663
              },
              {
                "candidateId": "dynamic-bt-h365-r1",
                "isDefault": true,
                "options": {
                  "halfLifeDays": 365,
                  "maxIterations": 300,
                  "ridge": 1,
                  "tolerance": 1e-9
                },
                "count": 17,
                "frequency": 0.20481927710843373
              }
            ]
          }
        },
        {
          "id": "neutral",
          "name": "Neutral 50/50",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.6931471805599356,
            "brier": 0.25,
            "accuracy": 0.5,
            "auc": 0.5
          },
          "pooledCoverage": 1,
          "tuning": {
            "matureEvents": 0,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 83,
              "warmupDefault": 0,
              "innerUnavailableDefault": 0,
              "innerSelected": 0
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              },
              "brier": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "neutral-default",
                "isDefault": true,
                "options": {},
                "count": 83,
                "frequency": 1
              }
            ]
          }
        }
      ],
      "caveats": [
        "This is algorithmically chronology-isolated retrospective set evaluation, not snapshot-verified historical evidence.",
        "Seeds without observation provenance before their own conservative event cutoff are excluded.",
        "Historical outcome source versions were fetched after the events; reported completion chronology cannot rule out later corrections.",
        "Target rows condition on realized matchups. They do not test pre-event bracket paths, title odds or top-eight odds.",
        "The grid and model families were designed after earlier 2018-2025 diagnostics, so this run is exploratory rather than confirmatory.",
        "Non-converged optimizer fits cannot enter configuration selection; an outer selected non-converged fit is explicitly scored as a neutral 0.5 fallback so all families retain identical target support.",
        "Hyperparameters are selected independently within each model family. No family is selected or productized."
      ],
      "sourceHashes": {
        "pointerSha256": "329cd2805b508d555d4fc6bcdda7b6c17ded7c77ef0f6cd45817d96a8dd97329",
        "runHash": "194fcc586f1e95a984fa0f1e5e54abe01143d11b21bb599a0b4e3aa6a0a135d4",
        "runSha256": "05925c70f121d4df3f555bdedf2dcf96ebd7b700815f541cda82c6136bc9f6c6",
        "forecastSha256": "018cd3121e25fd25f09c769d9777b5ce57127d0bad6ba5d42a3e1dbda6665d7d",
        "evaluationSha256": "e2677ffcc64d14217d237ea67d494141670b448da1ab476347550ce298f6cfd1",
        "reportSha256": "ff9c02dcb7e0f5984549da28f893d9543cabf007b9a8713e563cd58282a8738b",
        "engineManifestSha256": "d9b7fe4f3ab287204d0faf3424266f3e8986073c738291348fea99339c2cfa2b",
        "datasetSha256": "e21eb6bf8d91b295b875ab11959e1beddae937d7816e5c7da1a2f13db3f6371d",
        "datasetSemanticSha256": "19bdbde0b9755925c81ad40d64a4567fd1f35310b6034cc2a53bda5cc082b81b",
        "implementationSha256": "5a3ddd1fcbd91cf2cef5ad499c04a4529c0cbc915448c55253a9b97f7f8cc979",
        "tuningSpecFileSha256": "af62a6469227c850e84bc52fa95ff672b3a0237e7c9a8913e1b7ebf04e8d389e",
        "tuningSpecSemanticSha256": "30d52b2a2471c2db0aa2e3bda56e7098f2d7e7807f570c27af3f3c208311ce6a",
        "outcomeReconciliationSha256": "942d87117a89c80cddac3d7e310f23ee4fcdee4baf4c40cf9848ff2dafda60d0"
      }
    },
    {
      "id": "availability-assumed",
      "label": "Seed availability assumed",
      "description": "Exploratory retrospective assuming historical initial seeds were available",
      "allowHistoricalSeeds": true,
      "snapshotVerified": false,
      "selectedModel": null,
      "productize": false,
      "models": [
        {
          "id": "regularized-bt-recent-form",
          "name": "Regularized Bradley-Terry + seed + recent form",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5085230090712087,
            "brier": 0.16892140341305556,
            "accuracy": 0.746319445165672,
            "auc": 0.8201641272126822
          },
          "pooledCoverage": 0.48063185162436073,
          "tuning": {
            "matureEvents": 52,
            "fallbackEvents": 4,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 15,
              "innerSelected": 52
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.00479637408605827,
                "interval95": {
                  "lower": -0.022921965922866994,
                  "upper": 0.012285063172413704
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.001773979904267652,
                "interval95": {
                  "lower": -0.009419911691345751,
                  "upper": 0.005694868705257007
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "regularized-bt-default",
                "isDefault": true,
                "options": {
                  "abilityL2": 2,
                  "featureL2": 2,
                  "formHalfLifeDays": 180,
                  "formPrior": 6,
                  "formRatingK": 24,
                  "formRatingScale": 400,
                  "maxIterations": 300,
                  "tolerance": 1e-7
                },
                "count": 36,
                "frequency": 0.43373493975903615
              },
              {
                "candidateId": "regularized-bt-ability-l2-1",
                "isDefault": false,
                "options": {
                  "abilityL2": 1,
                  "featureL2": 2,
                  "formHalfLifeDays": 180,
                  "formPrior": 6,
                  "formRatingK": 24,
                  "formRatingScale": 400,
                  "maxIterations": 300,
                  "tolerance": 1e-7
                },
                "count": 27,
                "frequency": 0.3253012048192771
              },
              {
                "candidateId": "regularized-bt-form-half-life-365",
                "isDefault": false,
                "options": {
                  "abilityL2": 2,
                  "featureL2": 2,
                  "formHalfLifeDays": 365,
                  "formPrior": 6,
                  "formRatingK": 24,
                  "formRatingScale": 400,
                  "maxIterations": 300,
                  "tolerance": 1e-7
                },
                "count": 20,
                "frequency": 0.24096385542168675
              }
            ]
          }
        },
        {
          "id": "higher-seed",
          "name": "Higher seed",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5502986664453493,
            "brier": 0.1823943662672841,
            "accuracy": 0.7486847149622005,
            "auc": 0.7479228647928773
          },
          "pooledCoverage": 0.9089076123966832,
          "tuning": {
            "matureEvents": 0,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 83,
              "warmupDefault": 0,
              "innerUnavailableDefault": 0,
              "innerSelected": 0
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              },
              "brier": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "higher-seed-default",
                "isDefault": true,
                "options": {},
                "count": 83,
                "frequency": 1
              }
            ]
          }
        },
        {
          "id": "glicko2",
          "name": "Event-period Glicko-2",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5524903255444148,
            "brier": 0.1875557928899399,
            "accuracy": 0.7028992493838621,
            "auc": 0.788132780356054
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.00525618047072753,
                "interval95": {
                  "lower": -0.007871639823734866,
                  "upper": -0.002825108468792241
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.0013394384558493662,
                "interval95": {
                  "lower": -0.002101848787506338,
                  "upper": -0.0005687334289171762
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "glicko2-rd500",
                "isDefault": false,
                "options": {
                  "convergenceTolerance": 0.000001,
                  "initialRating": 1500,
                  "initialRd": 500,
                  "initialVolatility": 0.06,
                  "maxIterations": 100,
                  "ratingScale": 173.7178,
                  "tau": 0.5
                },
                "count": 67,
                "frequency": 0.8072289156626506
              },
              {
                "candidateId": "glicko2-rd350",
                "isDefault": true,
                "options": {
                  "convergenceTolerance": 0.000001,
                  "initialRating": 1500,
                  "initialRd": 350,
                  "initialVolatility": 0.06,
                  "maxIterations": 100,
                  "ratingScale": 173.7178,
                  "tau": 0.5
                },
                "count": 16,
                "frequency": 0.1927710843373494
              }
            ]
          }
        },
        {
          "id": "recency-elo",
          "name": "Recency-weighted Elo",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5822561188545007,
            "brier": 0.19723031509419217,
            "accuracy": 0.6993079542312147,
            "auc": 0.7793423070135965
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.020607326913651275,
                "interval95": {
                  "lower": -0.028142517600513846,
                  "upper": -0.01136044551783676
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.010089851512747511,
                "interval95": {
                  "lower": -0.011843045684254502,
                  "upper": -0.008203348579529625
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "recency-elo-k64-h730",
                "isDefault": false,
                "options": {
                  "halfLifeDays": 730,
                  "k": 64,
                  "scale": 400
                },
                "count": 67,
                "frequency": 0.8072289156626506
              },
              {
                "candidateId": "recency-elo-k32-h730",
                "isDefault": true,
                "options": {
                  "halfLifeDays": 730,
                  "k": 32,
                  "scale": 400
                },
                "count": 16,
                "frequency": 0.1927710843373494
              }
            ]
          }
        },
        {
          "id": "dynamic-bradley-terry",
          "name": "Dynamic Bradley-Terry",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.5935548858160498,
            "brier": 0.20506119489293312,
            "accuracy": 0.6485950482528792,
            "auc": 0.7267195423330035
          },
          "pooledCoverage": 0.49357065602008254,
          "tuning": {
            "matureEvents": 67,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 0,
              "warmupDefault": 16,
              "innerUnavailableDefault": 0,
              "innerSelected": 67
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": -0.01384443169032955,
                "interval95": {
                  "lower": -0.017804798177139383,
                  "upper": -0.009206226151694722
                },
                "status": "descriptive-paired-event-bootstrap"
              },
              "brier": {
                "estimate": -0.005989713485113392,
                "interval95": {
                  "lower": -0.007211223361240749,
                  "upper": -0.004729193900347815
                },
                "status": "descriptive-paired-event-bootstrap"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "dynamic-bt-h730-r1",
                "isDefault": false,
                "options": {
                  "halfLifeDays": 730,
                  "maxIterations": 300,
                  "ridge": 1,
                  "tolerance": 1e-9
                },
                "count": 66,
                "frequency": 0.7951807228915663
              },
              {
                "candidateId": "dynamic-bt-h365-r1",
                "isDefault": true,
                "options": {
                  "halfLifeDays": 365,
                  "maxIterations": 300,
                  "ridge": 1,
                  "tolerance": 1e-9
                },
                "count": 17,
                "frequency": 0.20481927710843373
              }
            ]
          }
        },
        {
          "id": "neutral",
          "name": "Neutral 50/50",
          "outerEvents": 83,
          "scoredOuterEvents": 83,
          "outerSets": 74891,
          "eventMacro": {
            "logLoss": 0.6931471805599356,
            "brier": 0.25,
            "accuracy": 0.5,
            "auc": 0.5
          },
          "pooledCoverage": 1,
          "tuning": {
            "matureEvents": 0,
            "fallbackEvents": 0,
            "selectionModes": {
              "fixed": 83,
              "warmupDefault": 0,
              "innerUnavailableDefault": 0,
              "innerSelected": 0
            },
            "versusDefault": {
              "betterWhen": "negative",
              "logLoss": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              },
              "brier": {
                "estimate": null,
                "interval95": null,
                "status": "not-available"
              }
            },
            "selectedSettings": [
              {
                "candidateId": "neutral-default",
                "isDefault": true,
                "options": {},
                "count": 83,
                "frequency": 1
              }
            ]
          }
        }
      ],
      "caveats": [
        "This is algorithmically chronology-isolated retrospective set evaluation, not snapshot-verified historical evidence.",
        "Historical initial-seed availability is assumed. This mode is not snapshot-safe and is not an unbiased historical backtest.",
        "Historical outcome source versions were fetched after the events; reported completion chronology cannot rule out later corrections.",
        "Target rows condition on realized matchups. They do not test pre-event bracket paths, title odds or top-eight odds.",
        "The grid and model families were designed after earlier 2018-2025 diagnostics, so this run is exploratory rather than confirmatory.",
        "Non-converged optimizer fits cannot enter configuration selection; an outer selected non-converged fit is explicitly scored as a neutral 0.5 fallback so all families retain identical target support.",
        "Hyperparameters are selected independently within each model family. No family is selected or productized."
      ],
      "sourceHashes": {
        "pointerSha256": "3cfe5aeb2be9fff32f6787fb76cb5630f4db3fc3b4d9577c98a9969e7bc441f9",
        "runHash": "3f6d9ef3b13becea3501df2afab2783bc94f42412d6edd05948563afb4a31115",
        "runSha256": "266173d8d45526a37d77f328b00bb137230db65fc517aa8dfd0219f07402b4e9",
        "forecastSha256": "73ded4c5d62bbbe94619c3e4c774aba8dada3276b89ac37f8b5219c378398a5d",
        "evaluationSha256": "4443594ae5be8d9269a5bc3758af28ffcb1af004200bdf2ec77168ede5a5d606",
        "reportSha256": "9578b87d0a8a73925231e52310f7b21fb74a086d6d81375ed0a732db0e4c2e5a",
        "engineManifestSha256": "34dac510000e52d25ea15b1085835467be70af0efb3b2f47651a0c7391a8a3cf",
        "datasetSha256": "e21eb6bf8d91b295b875ab11959e1beddae937d7816e5c7da1a2f13db3f6371d",
        "datasetSemanticSha256": "19bdbde0b9755925c81ad40d64a4567fd1f35310b6034cc2a53bda5cc082b81b",
        "implementationSha256": "5a3ddd1fcbd91cf2cef5ad499c04a4529c0cbc915448c55253a9b97f7f8cc979",
        "tuningSpecFileSha256": "af62a6469227c850e84bc52fa95ff672b3a0237e7c9a8913e1b7ebf04e8d389e",
        "tuningSpecSemanticSha256": "30d52b2a2471c2db0aa2e3bda56e7098f2d7e7807f570c27af3f3c208311ce6a",
        "outcomeReconciliationSha256": "942d87117a89c80cddac3d7e310f23ee4fcdee4baf4c40cf9848ff2dafda60d0"
      }
    }
  ]
} satisfies TournamentPredictionBacktestBundle;
